# start src/nanoclaw/types.py
"""Domain models for NanoClaw.

Replaces src/types.ts from the TypeScript implementation.
All models use Pydantic v2 for runtime validation.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class AdditionalMount(BaseModel):
    """A filesystem mount to add to agent containers.

    Attributes:
        host_path: Absolute path on the host (supports ~ for home directory).
        container_path: Mount destination inside container. Defaults to basename
            of host_path under /workspace/extra/.
        readonly: Whether to mount read-only. Defaults to True for safety.
    """

    host_path: str
    container_path: str | None = None
    readonly: bool = True


class AllowedRoot(BaseModel):
    """An allowed root directory for container mounts.

    Attributes:
        path: Absolute path or ~ for home (e.g., ~/projects).
        allow_read_write: Whether read-write mounts are permitted under this root.
        description: Optional human-readable description.
    """

    path: str
    allow_read_write: bool = False
    description: str | None = None


class MountAllowlist(BaseModel):
    """Security allowlist for additional container mounts.

    Stored at ~/.config/nanoclaw/mount-allowlist.json — NOT mounted into containers
    so agents cannot tamper with it.

    Attributes:
        allowed_roots: Directories that may be mounted into containers.
        blocked_patterns: Glob patterns for paths that must never be mounted.
        non_main_read_only: If True, non-main groups always get read-only mounts.
    """

    allowed_roots: list[AllowedRoot] = Field(default_factory=list)
    blocked_patterns: list[str] = Field(default_factory=list)
    non_main_read_only: bool = True


class ContainerConfig(BaseModel):
    """Per-group container configuration.

    Attributes:
        additional_mounts: Extra filesystem mounts to include.
        timeout: Container timeout in milliseconds. Defaults to None (use global).
    """

    additional_mounts: list[AdditionalMount] | None = None
    timeout: int | None = None


class RegisteredGroup(BaseModel):
    """A WhatsApp group registered with NanoClaw.

    Attributes:
        name: Human-readable group name.
        folder: Filesystem folder name under groups/.
        trigger: Trigger pattern string (e.g., "@Andy").
        added_at: ISO timestamp when the group was registered.
        container_config: Optional per-group container overrides.
        requires_trigger: Whether the bot requires an @mention trigger.
            Defaults to True for groups, False for solo chats.
    """

    name: str
    folder: str
    trigger: str
    added_at: str
    container_config: ContainerConfig | None = None
    requires_trigger: bool | None = None


class NewMessage(BaseModel):
    """An inbound message from a WhatsApp chat.

    Attributes:
        id: WhatsApp message ID.
        chat_jid: JID of the chat/group this message belongs to.
        sender: JID of the sender.
        sender_name: Display name of the sender.
        content: Text content of the message.
        timestamp: ISO timestamp string.
        is_from_me: Whether this message was sent by the bot's own number.
        is_bot_message: Whether this message was generated by the bot.
    """

    id: str
    chat_jid: str
    sender: str
    sender_name: str
    content: str
    timestamp: str
    is_from_me: bool = False
    is_bot_message: bool = False


class ScheduledTask(BaseModel):
    """A scheduled task stored in the database.

    Attributes:
        id: Unique task identifier.
        group_folder: Folder name of the group that owns this task.
        chat_jid: JID to send results to.
        prompt: The prompt to send to the agent.
        schedule_type: One of 'cron', 'interval', or 'once'.
        schedule_value: Cron expression, milliseconds, or ISO timestamp.
        context_mode: 'group' reuses the group session; 'isolated' starts fresh.
        next_run: ISO timestamp for the next scheduled run, or None if done.
        last_run: ISO timestamp of the last run, or None if never run.
        last_result: Summary of the last run result, or None.
        status: One of 'active', 'paused', or 'completed'.
        created_at: ISO timestamp when the task was created.
    """

    id: str
    group_folder: str
    chat_jid: str
    prompt: str
    schedule_type: str  # 'cron' | 'interval' | 'once'
    schedule_value: str
    context_mode: str = "isolated"  # 'group' | 'isolated'
    next_run: str | None = None
    last_run: str | None = None
    last_result: str | None = None
    status: str = "active"  # 'active' | 'paused' | 'completed'
    created_at: str


class TaskRunLog(BaseModel):
    """A log entry for a single scheduled task run.

    Attributes:
        task_id: ID of the task that was run.
        run_at: ISO timestamp when the run started.
        duration_ms: Duration of the run in milliseconds.
        status: 'success' or 'error'.
        result: Result text, or None.
        error: Error message, or None.
    """

    task_id: str
    run_at: str
    duration_ms: int
    status: str  # 'success' | 'error'
    result: str | None = None
    error: str | None = None


class VolumeMount(BaseModel):
    """A filesystem volume mount for an agent container.

    Attributes:
        host_path: Absolute path on the host filesystem.
        container_path: Mount destination inside the container.
        readonly: Whether the mount is read-only.
    """

    host_path: str
    container_path: str
    readonly: bool = False


class ContainerInput(BaseModel):
    """Input data passed to an agent container via stdin.

    Attributes:
        prompt: The initial prompt for the agent.
        session_id: Optional Claude session ID to resume.
        group_folder: Folder name of the group running this agent.
        chat_jid: JID of the chat that triggered this run.
        is_main: Whether this is the main group (with elevated permissions).
        is_scheduled_task: Whether this is a scheduled (not user-triggered) run.
        secrets: API keys passed via stdin only — never written to disk.
    """

    prompt: str
    session_id: str | None = None
    group_folder: str
    chat_jid: str
    is_main: bool
    is_scheduled_task: bool = False
    secrets: dict[str, str] | None = None


class ContainerOutput(BaseModel):
    """Output data from an agent container, parsed from stdout markers.

    Attributes:
        status: 'success' or 'error'.
        result: Agent response text, or None.
        new_session_id: Updated session ID from this run, if any.
        error: Error message, or None.
    """

    status: str  # 'success' | 'error'
    result: str | None = None
    new_session_id: str | None = None
    error: str | None = None


class AvailableGroup(BaseModel):
    """A WhatsApp group available for registration.

    Attributes:
        jid: WhatsApp JID of the group.
        name: Display name of the group.
        last_activity: ISO timestamp of last message activity.
        is_registered: Whether this group is already registered with NanoClaw.
    """

    jid: str
    name: str
    last_activity: str
    is_registered: bool


class ChatInfo(BaseModel):
    """Summary row from the chats table.

    Attributes:
        jid: WhatsApp JID.
        name: Display name.
        last_message_time: ISO timestamp of most recent message.
    """

    jid: str
    name: str
    last_message_time: str


class IpcMessage(BaseModel):
    """An IPC message file written by a container agent.

    Attributes:
        type: Message type discriminator.
        chat_jid: Target JID to send the message to.
        text: Message text content.
    """

    type: str
    chat_jid: str
    text: str


class IpcScheduleTask(BaseModel):
    """IPC request to schedule a new task.

    Attributes:
        type: Always 'schedule_task'.
        prompt: Task prompt.
        schedule_type: 'cron', 'interval', or 'once'.
        schedule_value: Cron expression, ms interval, or ISO timestamp.
        context_mode: 'group' or 'isolated'.
        target_jid: JID of the chat to run the task for.
    """

    type: str
    prompt: str
    schedule_type: str
    schedule_value: str
    context_mode: str = "isolated"
    target_jid: str


class IpcTaskAction(BaseModel):
    """IPC request to pause, resume, or cancel a task.

    Attributes:
        type: 'pause_task', 'resume_task', or 'cancel_task'.
        task_id: ID of the task to act on.
    """

    type: str
    task_id: str


class IpcRegisterGroup(BaseModel):
    """IPC request to register a new group (main group only).

    Attributes:
        type: Always 'register_group'.
        jid: WhatsApp JID of the group to register.
        name: Display name.
        folder: Filesystem folder name.
        trigger: Trigger pattern string.
        requires_trigger: Whether trigger is required.
        container_config: Optional per-group container configuration.
    """

    type: str
    jid: str
    name: str
    folder: str
    trigger: str
    requires_trigger: bool | None = None
    container_config: ContainerConfig | None = None


# end src/nanoclaw/types.py
